-- DROP ALL PROCEDURES

DROP PROCEDURE IF EXISTS is_snake_eat_the_food;
DROP PROCEDURE IF EXISTS get_snake_direction;
DROP PROCEDURE IF EXISTS initialize_board;
DROP PROCEDURE IF EXISTS initialize_snake;
DROP PROCEDURE IF EXISTS initialize_food;
DROP PROCEDURE IF EXISTS initialize_control;
DROP PROCEDURE IF EXISTS play;
DROP PROCEDURE IF EXISTS play_default;
DROP PROCEDURE IF EXISTS spawn_snake;
DROP PROCEDURE IF EXISTS snake_grow;
DROP PROCEDURE IF EXISTS snake_move;
DROP PROCEDURE IF EXISTS spawn_food;
DROP PROCEDURE IF EXISTS move_food;
DROP PROCEDURE IF EXISTS get_food_position_by_id;
DROP PROCEDURE IF EXISTS get_snake_last_body_position;
DROP PROCEDURE IF EXISTS get_snake_first_body_position;
DROP PROCEDURE IF EXISTS get_snake_body_position_by_id;
DROP PROCEDURE IF EXISTS get_snake_next_position;
DROP PROCEDURE IF EXISTS move_left;
DROP PROCEDURE IF EXISTS move_right;
DROP PROCEDURE IF EXISTS move_up;
DROP PROCEDURE IF EXISTS move_down;
DROP PROCEDURE IF EXISTS board_clear;
DROP PROCEDURE IF EXISTS board_simulate_object;
DROP PROCEDURE IF EXISTS display;
DROP PROCEDURE IF EXISTS get_board_size;


